version: "3"
services:
  minio:
    image: minio/minio
    volumes:
      - ../docker/minio/data:/data
      - ../docker/minio/config:/root/.minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin1234
      MINIO_STORAGE_USE_HTTPS: "false"
    networks:
      - net1
    command: server /data

  fastapi:
    image: fastapi
    ports:
      - 5000:80
    networks:
      - net1
    container_name: fastapi

  jupyter-lab:
    image: "jupyter-image"
    container_name: jupyter-lab
    volumes:
      - ../docker/jupyter_data:/home/jovyan/work
    ports:
      - 8888:8888
    networks:
      - net1
    environment:
      - JUPYTER_ENABLE_LAB=yes

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ../docker/redis-data:/var/lib/redis
      - ../docker/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - net1

networks:
  net1:
    driver: bridge
